services:
  backend:
    build: ./backend
    restart: always
    expose:
      - "3000"
    networks:
      - my-network
    environment:
      NODE_ENV: production

  frontend:
    build: ./frontend
    restart: always
    expose:
      - "80"
    networks:
      - my-network
    environment:
      VITE_API_URL: /api  # Pedís al proxy en /api, no directo al backend

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - my-network
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
    entrypoint: >
      sh -c "certbot certonly --webroot
             --webroot-path=/var/www/html
             --email tu-correo@uns.edu.ar --agree-tos --no-eff-email
             -d server.cienciasdelasalud.uns.edu.ar"

networks:
  my-network:
    driver: bridge
